# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-16 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('name_cn', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='\u4e2d\u6587\u540d')),
                ('password', models.CharField(max_length=128, verbose_name='\u5bc6\u7801')),
                ('position', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='\u804c\u4f4d')),
                ('qq', models.CharField(blank=True, max_length=20, null=True, verbose_name='QQ\u53f7\u7801')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('tel', models.CharField(blank=True, max_length=20, verbose_name='\u529e\u516c\u7535\u8bdd')),
            ],
        ),
    ]
